

SURFACE_TITLE = "RENDERING DEMOS"
SCREEN_W, SCREEN_H = 1280, 720
DEMO_SECTIONS = ["pygame feautures", "My Demo"]

POINT_RADIUS = 3
POINT_COL = "#39cc9b"
LINE_WIDTH = 1
LINE_COL =  "#39cc9b"

CENTER_W = SCREEN_W / 2
CENTER_H = SCREEN_H / 2

