DEFAULT_FONT = "jetbrainsmononerdfont"

SURFACE_TITLE = "GRAPHIC RENDERING PRACTICES"

SCREEN_W = 1280
SCREEN_H = 720
HALF_W = SCREEN_W // 2
HALF_H = SCREEN_H // 2
COORDINATE_UNIT_AMOUNT = 10
COORDINATE_UNIT_SEGMENT_LEN = 5
MAX_AXIS_LEN = 720 # max len of x, y, z axis
HALF_AXIS_LEN = MAX_AXIS_LEN // 2 # max len of x, y, z axis

POINT_RADIUS = 3
POINT_COL = "#39cc9b"

LINE_WIDTH = 1
LINE_COL =  "#39cc9b"


